vich_uploader:
    db_driver: orm

    mappings:
        downloads:
            uri_prefix: /downloads/files
            upload_destination: '%kernel.project_dir%/downloads'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true
