#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /willkommen.htm
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: landingPage
    permanent: true
    keepQueryParams: true