name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        id: composer-validation
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        id: composer-install
        env:
          APP_ENV: ${{ secrets.APP_ENV }}
          APP_DEBUG: ${{ secrets.APP_DEBUG }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          VAR_DUMPER_FORMAT: ${{ secrets.VAR_DUMPER_FORMAT }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_RECAPTCHA_SITE_KEY: ${{ secrets.GOOGLE_RECAPTCHA_SITE_KEY }}
          GOOGLE_RECAPTCHA_SECRET: ${{ secrets.GOOGLE_RECAPTCHA_SECRET }}
          EWZ_RECAPTCHA_SITE_KEY: ${{ secrets.EWZ_RECAPTCHA_SITE_KEY }}
          EWZ_RECAPTCHA_SECRET: ${{ secrets.EWZ_RECAPTCHA_SECRET }}
          MAILER_DSN: ${{ secrets.MAILER_DSN }}
          CONTACT_FORM_TO: ${{ secrets.CONTACT_FORM_TO }}
          CONTACT_FORM_FROM: ${{ secrets.CONTACT_FORM_FROM }}
        run: composer install --prefer-dist --no-progress

      - name: run phpstan checks
        id: phpstan-checks
        run: ./vendor/bin/phpstan analyse src --level 3

      #    - name: cache warmup
      #      run: ./bin/console cache:clear

#      - name: install npm packages
#        id: npm-clean-install
#        run: npm ci
#
#      - name: build assets with encore
#        run: ./node_modules/.bin/encore production

      - name: push to production
        run: rsync -chavzP -e 'ssh -p 2244'  --stats . webdniw8j_q5cxrj@webdniw8j.wh.hosting.zone:/home/webdniw8j/v2

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
